---

env:
  global:
    - CC_TEST_REPORTER_ID=382fbaf36ba35e7f049312872e9ed5d49309b54db5a29d0fb74622f4022d12d2

language: node_js

node_js:
  - node

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
